[option]
exclude_paths = ["dv/.*"]

[textrules]

[syntaxrules]
procedural_continuous_assignment = true
action_block_with_side_effect = true
keyword_forbidden_wire_reg = true
module_nonansi_forbidden = true
